### ISSUE TITLE
[Discussion] How should we evaluate "completeness"?

### ISSUE THREAD

**Issue by idunbarh** [CISA-SBOM-Community/SBOM-Generation#19]
We need a automated method for evaluation "completeness" of SBOMs which can be incorporated into a pipeline. 

The following tools have quality checks:
- [sbomqs](https://github.com/interlynk-io/sbomqs)
- [sbom-utility](https://github.com/CycloneDX/sbom-utility)

Ideally we be able to determine if we're meeting all minimum requirements of [Framing Software Component Transparency Third Edition (DRAFT)](https://docs.google.com/document/d/1uddfhPqflTOeYK7ZJjS4gGa8pspwez6mhJUjTrvu4J4/edit?usp=sharing) but tooling probably doesn't support these checks.

Another option of completeness is the [BOM Maturity Model](https://scvs.owasp.org/bom-maturity-model/) which is being incorporated into [sbomqs](https://github.com/interlynk-io/sbomqs).

Are there other ways we could measure completeness of SBOMs today in a pipeline?

**Comment by tiegz** [comment]
Do we care about SBOM spec validation at all? I just noticed that sbomqs will [only check that the version of the declared SBOM spec is supported](https://github.com/interlynk-io/sbomqs/blob/cb796449b745ac0f2556643837ab63ce16a81080/pkg/scorer/structural.go#L31-L33), but it doesn't actually do validation against that spec.

There's an issue to add support here: https://github.com/interlynk-io/sbomqs/issues/248

I noticed this when sbom-utility raised some spec errors on an SBOM that were not reported by sbomqs:

```
[INFO] Too many errors. Showing (10/2099) errors.
1. {
        "type": "unique",
        "field": "dependencies.1.dependsOn",
        "context": "(root).dependencies.1.dependsOn",
        "description": "array items[0,1] must be unique",
        "value": {
            "type": "array",
            "index": 0,
            "item": "pkg:npm/negotiator@0.6.2"
        }
    }
```

**Comment by riteshnoronha** [comment]
@tiegz yes this is accurate `sbomqs` does not validate against the spec. This was intentional on our part. Our reasoning was as follows

- The validating against the schema, checks for every field of the sbom. While this is great, the tool, was written to check for compliance standards, like NTIA, BSI. These standards currently don't go beyond metadata/components/dependencies. 
- These schemas are only available for cyclonedx, spdx nothing official exists. This will change with spdx3.0.
- The issue above is interesting, we should add that as a quality metric. 

We think of validating a sbom with a schema as a pre-step to scoring. This is how we plan to implement it. It will however be optional.

-Ritesh
(author sbomqs)
